version: '3.4'

services:
  onlineretailsystem.host:
    environment:
      POSTGRES_CONNECTION: User ID=postgres;Password=postgres;Host=db;Port=5432;Database=postgres;Pooling=true;Connection Lifetime=0;
      SKIP_SEEDING: true
    image: ${DOCKER_REGISTRY-}onlineretailsystemhost
    build:
      context: .
      dockerfile: OnlineRetailSystem.Host/Dockerfile


  onlineretailsystem.host2:
    environment:
      POSTGRES_CONNECTION: User ID=postgres;Password=postgres;Host=db;Port=5432;Database=postgres;Pooling=true;Connection Lifetime=0;
    image: ${DOCKER_REGISTRY-}onlineretailsystemhost
    build:
      context: .
      dockerfile: OnlineRetailSystem.Host/Dockerfile

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./postgres-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080